Product list
JakubSQ/RubyLoversShop pull request #1
Opened 2021-05-23 19:36 UTC by JakubSQ

2021-05-24 07:36 UTC, oskarlakner commented on Gemfile
> +gem 'graphicsmagick'
po co są te biblioteki?

2021-05-24 07:43 UTC, oskarlakner requested changes
<img width="1057" alt="Screenshot 2021-05-24 at 09 39 03" src="https://user-images.githubusercontent.com/5034850/119313461-e1c55900-bc73-11eb-923d-7bd6e2419db7.png">

Ogólnie dobra robota, gdyby nie:
- niedokladnie przeczytales tresc zadania. Dodales funkcjonalnosc o jaka nie byles proszony - upload zdjec, w dodatku nie zapytales o to jak nalezy upload zrealizowac. W zespole produktowym takie rzeczy trzeba zawsze uzgodnic, bo sa uzaleznione od infrastruktury aplikacji
- nie sprawdziles co commitujesz, a to jest najbardziej podstawowy grzech - review to czas reviwera, nie sprawdzajac plikow wczesniej pokazujesz bardzo wyraznie w zespole swoje niedbalstwo

2021-05-24 07:43 UTC, oskarlakner commented on mkmf.log
> +find_executable: checking for gm... -------------------- yes
sprawdzales co commitujesz? :)

2021-05-24 07:43 UTC, oskarlakner commented on spec/controllers/pages_controller_spec.rb
> +    before { create(:product) }
poczytaj o letach - to jest dziwne

2021-05-24 07:43 UTC, oskarlakner commented on spec/requests/products_request_spec.rb
> +RSpec.describe "Products", type: :request do
a to co?

2021-05-24 07:43 UTC, oskarlakner commented on spec/models/product_spec.rb
> +  subject { build(:product)}
tutaj tez moglbys let uzyc

2021-05-25 06:08 UTC, JakubSQ commented on Gemfile
> +gem 'graphicsmagick'
Proba zrobienia wszsytkich zdjec w jednym rozmiarze ale niestety gem nie chcial wspolpracowac ze mna

2021-05-25 06:13 UTC, JakubSQ commented on mkmf.log
> +find_executable: checking for gm... -------------------- yes
1. Chyba za bardzo zasugerowalem sie tutorialami gdzie wszyscy robili upload zdjec. Masz tu dobry sposob prowadzenia taskow, gdzie nie ma prowadzenia za raczke. Jednak na te chwile jeszcze nie wiem na ile cos jest potrzebne do zrobienia aby osiagnac cel, a na ile cos moze byc juz dodatkowa i niepotrzebna praca - spowodowane to jest brakiem wiedzy i doswiadczenia. /w zadnym wypadku sie nei usprawiedliwiam/

2021-05-25 06:15 UTC, JakubSQ commented on mkmf.log
> +find_executable: checking for gm... -------------------- yes
Zgadza sie nie sprawdzilem - nauka na przyszlosc.

2021-05-25 06:15 UTC, JakubSQ commented on spec/requests/products_request_spec.rb
> +RSpec.describe "Products", type: :request do
do wyrzucenia caly folder - tak mi sie wydaje

2021-05-25 06:16 UTC, JakubSQ commented on spec/controllers/pages_controller_spec.rb
> +    before { create(:product) }
ok

2021-05-25 06:16 UTC, JakubSQ commented on spec/models/product_spec.rb
> +  subject { build(:product)}
ok

2021-05-25 18:23 UTC, oskarlakner approved these changes

2021-05-25 18:23 UTC, oskarlakner requested changes
Checki masz na czerwono ;)

2021-05-28 08:53 UTC, oskarlakner approved these changes

2021-05-31 14:39 UTC, merged