Feat/changing quantity in shopping cart
JakubSQ/RubyLoversShop pull request #24
Opened 2021-11-04 15:12 UTC by JakubSQ

TASK No. 1 - Change number of products in the shopping cart
Opis:
As a shopper, I want to be able to easily change the number of items of any product present in my shopping cart

Acceptance criteria:
- A shopper can change the number of items of the given product from their shopping cart
- Changing the number to zero removes the product from the shopping cart
- There is a system & request spec

TASK No. 2 - Remove product from the shopping cart

Opis:
As a shopper, I want to be able to easily remove a given product from my shopping cart

Acceptance criteria:
- A shopper can remove a product from their shopping cart with one click, regardless of the number of items of this product present in their cart
- There is a system & request spec

2021-11-05 09:54 UTC, kamilpuchala requested changes
GJ, but small improvements are needed

2021-11-05 09:54 UTC, kamilpuchala commented on .rubocop.yml
> +Metrics/AbcSize:
I say NO NO NO!
If there is a method which you need to have disabled this cop just do it, but set it up globally it's not a good option.

2021-11-05 09:54 UTC, kamilpuchala commented on app/controllers/line_items_controller.rb
> +      @line_item.destroy if @line_item.quantity.zero?
It isn't the best option. If someone set the quantity to 0 you will make 2 operations in DB

2021-11-05 09:54 UTC, kamilpuchala commented on app/controllers/line_items_controller.rb
> +      flash[:alert] = 'Please, type positive value.'
I'm not sure if this alert is correct? Maybe will be better to display an error here

2021-11-05 09:54 UTC, kamilpuchala commented on app/controllers/line_items_controller.rb
> +      flash[:alert] = 'Please, type positive value.'
Btw. in validation in model you have message which is already set

2021-11-05 09:54 UTC, kamilpuchala commented on app/services/cart_services.rb
> +      if full_validation?
what `full_validation?` mean? It suggest that you can have 2 types of validation, part validation and full_validation.
The name of this method isn't correct in my opinion

2021-11-05 09:54 UTC, kamilpuchala commented on app/services/checkout_services.rb
> +      if cart.line_items.present?
😮 it needs refactor

2021-11-05 09:54 UTC, kamilpuchala commented on app/views/line_items/_line_item.html.erb
> +                <%= f.number_field :quantity, { value: line_item.quantity, onchange: 'this.form.submit();' } %>
👍

2021-11-05 09:54 UTC, kamilpuchala commented on spec/requests/line_item_quantity_cart_request_spec.rb
> +  let(:line_item) { LineItem.create(cart_id: cart.id, product_id: product.id, quantity: 10) }
This should be set as a factory

2021-11-05 09:54 UTC, kamilpuchala commented on spec/requests/line_item_quantity_cart_request_spec.rb
> +    context 'is allowed to' do
There is progress in your rspec descriptions, but it shouldn't be a context.
It will be nice if you will add this cop to your rubopcop: https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ContextWording it's a good practice in ruby world.
Of course, you can has your own rules, but it's better to has similar than others :)

2021-11-05 09:54 UTC, kamilpuchala commented on spec/requests/line_item_quantity_cart_request_spec.rb
> +    context 'is allowed to' do
If you will decide to do it, you will has some refactors, but it's nice to train descriptions

2021-11-18 08:54 UTC, oskarlakner commented on spec/system/line_item_quantity_cart_spec.rb
> +      driven_by(:selenium_chrome_headless)
a moze da sie jakos zrobic z devise, aby user od razu byl zalogowany? :)

2021-11-18 08:55 UTC, oskarlakner commented on spec/requests/line_item_quantity_cart_request_spec.rb
> +        patch "/line_items/#{line_item.id}", params: { line_item: { quantity: -1 } }
to wyglada jak powtarzajacy sie kod. Moze dalobys rade przeniesc go do subjecta?

2021-11-18 09:01 UTC, oskarlakner commented on app/services/checkout_services.rb
>  module CheckoutServices
**To nie jest coś co musisz zaadresować.** Z reguly nie powinno sie dodawac suffixa _services, tak samo jak nie dodajesz do _model. Nie tyczy sie to serializerow, decoratorow itd. ALE, jak to w programowaniu, znajdziesz i zwolennikow uzywania _services, mnie natomiast nigdy nie przekonali 😅

2021-11-18 09:01 UTC, oskarlakner commented on app/services/checkout_services.rb
> +    def order_assignment
imo it's rather "create order"

2021-11-18 09:01 UTC, oskarlakner commented on app/services/checkout_services.rb
> +    def line_item_update
a tutaj `update_line_item`

2021-11-18 09:02 UTC, oskarlakner commented on app/services/checkout_services.rb
> +      @cart = cart
Nie powinno sie przekazywac parametrow do konstruktora. Dlaczego nie chcesz tych paramsow przekazac do call?

2021-11-18 09:02 UTC, oskarlakner approved these changes
generalnie jest ok, ale posiedzialbym jeszcze chwile nad tym kodem :)

2021-11-19 20:12 UTC, kamilpuchala approved these changes

2021-11-19 20:12 UTC, kamilpuchala commented on app/services/line_item_remover.rb
> +module LineItemRemover
Here andd in next class.
WDYT about concept like:
module LineItems
 class Delete(eventually DeleteLineItem)

and
module LineItems
  class Update

2021-11-19 20:12 UTC, kamilpuchala commented on app/services/checkout_creator.rb
> +module CheckoutCreator
It create Checkout? Or seting ordeR? Im conffused

2021-11-20 11:30 UTC, merged